### PR TITLE
Feature/change country from detail

### PR DESCRIPTION
**Pull request by apercas**
This feature adds a dropdown with a list of countries so the user can switch from the current one to another from the country profile:
image

Requires `chosen` so you might need to run `bundle install`

### CODE REVIEW

**Comment by davidsingal** [comment]
could you add chosen plugin in homepage's module? And remove "topic" from menu please.

**Comment by apercas** [comment]
@davidsingal Sure! it should be easily duplicable :) And of course, I asked what to do with that link but nobody knew anything so I kept it pointing to `#` :D

**Comment by davidsingal** [comment]
It is a kind of filter, we can make this in another PR. Thanks!

**Comment by apercas** [comment]
Done:
image

**Pull request merged**
